package:
  name: conda-verify
  version: "2.1.0"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python


build:
  script: pip install . --no-deps

about:
  home: https://github.com/conda/conda-verify
  license: BSD
  license_file: LICENSE.txt