package:
  name: conda-verify
  version: "2.0.1"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python


build:
  script: python setup.py install

about:
  home: https://github.com/conda/conda-verify
  license: BSD
  license_file: LICENSE.txt