- name: Michael Sarahan
  email: msarahan@gmail.com
  github: msarahan
  alternate_emails:
  - msarahan@continuum.io
  - msarahan@anaconda.com
  aliases:
  - Mike Sarahan
  num_commits: 9
  first_commit: 2019-01-03 20:00:40
- name: Mandeep Bhutani
  email: mbhutani@continuum.io
  github: mandeep
  aliases:
  - mandeep
  alternate_emails:
  - mandeep@users.noreply.github.com
- name: Ilan Schnell
  email: ilanschnell@gmail.com
  alternate_emails:
  - ilan@continuum.io
   
